name: flutter_plugin_pos_integration_example
description: Demonstrates how to use the flutter_plugin_pos_integration plugin.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.16.9"

dependencies:
  flutter:
    sdk: flutter

  flutter_plugin_pos_integration:
    path: ../

  cupertino_icons: ^1.0.6
  permission_handler: ^11.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true