name: flutter_plugin_pos_integration
description: IDeploy Flutter POS integration
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

  ideploy_package:
    git:
      url: git@github.com:Ideploy22/flutter-lib-common-packages.git
      ref: main

  plugin_platform_interface: ^2.1.5


dev_dependencies:
  build_runner: ^2.3.3
  dart_code_metrics: ^5.7.3
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.1.5
  json_serializable: ^6.6.2


flutter:
  plugin:
    platforms:
      android:
        package: br.ideploy.pos.integration.flutter_plugin_pos_integration
        pluginClass: FlutterPluginPosIntegrationPlugin